#!/usr/bin/env julia
#
# Emit the `[province_isolation_history]` and `[province_bed_capacity_history]`
# blocks for data/observations.toml from data/province_care_scanned.csv, the
# per-province isolation occupancy and bed figures scanned by
# scripts/scan_province_care.jl and checked against a blind second read.
#
# Each block is sparse: one `[block.province]` sub-table per province with its
# own `dates` and `values`, since the reports print the figures for different
# provinces on different days. A province with no printed figure on a day has
# no entry. Both blocks are printed to stdout for pasting into the manifest,
# as scan_province_lab.jl does for the laboratory block.
#
# Usage:
#
#   julia --project=scripts scripts/province_care_manifest.jl [csv]

using CSV
using DataFrames
using Dates

const ROOT = normpath(joinpath(@__DIR__, ".."))
const CARE_CSV = length(ARGS) >= 1 ? ARGS[1] :
    joinpath(ROOT, "data", "province_care_scanned.csv")

const KEYS = Dict(
    "Ituri" => "ituri", "Nord-Kivu" => "nord_kivu", "Sud-Kivu" => "sud_kivu",
    "Haut-Uele" => "haut_uele", "Tshopo" => "tshopo", "Bas-Uele" => "bas_uele",
    "Sud Ubangi" => "sud_ubangi",
)
const ORDER = [
    "ituri", "nord_kivu", "sud_kivu", "haut_uele", "tshopo", "bas_uele",
    "sud_ubangi",
]

function series(df, column)
    out = Dict{String, Vector{Tuple{Date, Int}}}()
    for row in eachrow(df)
        v = row[column]
        ismissing(v) && continue
        key = get(KEYS, String(row.province), nothing)
        key === nothing && error("unknown province `$(row.province)`")
        push!(get!(out, key, Tuple{Date, Int}[]), (Date(row.report_date), Int(v)))
    end
    for (key, pairs) in out
        sort!(pairs; by = first)
        dates = first.(pairs)
        allunique(dates) || error(
            "province `$(key)` has more than one `$(column)` on one date: " *
                "$(dates[findall(d -> count(==(d), dates) > 1, dates)])"
        )
    end
    return out
end

function emit(io, block, comment, source, data)
    println(io, comment)
    println(io, "[", block, "]")
    println(io, "source = \"", source, "\"")
    for key in ORDER
        haskey(data, key) || continue
        pairs = data[key]
        println(io)
        println(io, "[", block, ".", key, "]")
        println(io, "dates = [", join(("\"$(d)\"" for (d, _) in pairs), ", "), "]")
        println(io, "values = [", join((v for (_, v) in pairs), ", "), "]")
    end
    return println(io)
end

function main()
    df = CSV.read(
        CARE_CSV, DataFrame; types = Dict(
            :patients_isolated => Union{Missing, Int},
            :beds => Union{Missing, Int},
            :sitrep => Int,
        )
    )
    isolation = series(df, :patients_isolated)
    beds = series(df, :beds)
    println("===== paste into data/observations.toml =====\n")
    emit(
        stdout, "province_isolation_history",
        """
        # Per-province patients in isolation at the end of the day, from the
        # occupation table of the INSP situation reports (Tableau IV, V, 5, 6
        # or 7 by vintage, to SitRep 080) and the per-province care-continuity
        # prose from SitRep 081. Generated by
        # `julia --project=scripts scripts/province_care_manifest.jl` from
        # data/province_care_scanned.csv. One sub-table per province with its
        # own dates, since coverage differs by province and by day; a province
        # that prints nothing on a day has no entry. Where a report separates
        # patients in normed structures from the total hospitalised (Nord-Kivu
        # from SitRep 124), the value is the total, which is what the national
        # tile counts. Fitted as a split of the printed sum of the provinces
        # present each day, alongside the national isolation_history.""",
        "INSP situation reports, occupation table (Patients en isolement, Fin J) to SitRep 080 and Continuité des soins / Prise en charge holistique prose from SitRep 081, per province; scanned by scripts/scan_province_care.jl and checked against an independent blind read (data/province_care_scanned.csv).",
        isolation
    )
    emit(
        stdout, "province_bed_capacity_history",
        """
        # Per-province isolation and treatment beds (`lits`), printed with the
        # occupancy rate in the same table and prose as the occupancy above,
        # or implied by it as occupancy / rate in the early tables. Generated
        # by `julia --project=scripts scripts/province_care_manifest.jl`. The
        # national bed_capacity_history is the sum over the provinces that
        # print a figure on a day; this block keeps the split. Nord-Kivu's
        # count from SitRep 124 is the beds in normed structures, the figure
        # its printed rate refers to. Fitted as a split of the printed sum of
        # the provinces present each day, over per-patch capacity walks.""",
        "INSP situation reports, per-province bed counts (lits) from the occupation table and the care-continuity prose; scanned by scripts/scan_province_care.jl and checked against an independent blind read (data/province_care_scanned.csv).",
        beds
    )
    for (name, data) in (("isolation", isolation), ("beds", beds))
        n = sum(length(v) for v in values(data); init = 0)
        println(stderr, "$(name): $(n) entries over $(length(data)) provinces")
    end
    return nothing
end

main()
